name: KICS IaC Security Scan
on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  kics-scan:
    runs-on: ubuntu-latest
    name: Run KICS Scan
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create results directory
        run: mkdir -p results-dir

      - name: List files for debugging
        run: |
          echo "Files in repository:"
          find . -name "*.tf" -o -name "Dockerfile*" -o -name "*.yaml" -o -name "*.yml" | head -20

      - name: Run KICS Scan
        uses: Checkmarx/kics-github-action@v1.7.0
        continue-on-error: false   # ✅ prevents failure
        with:
          path: '.'
          output_path: results-dir
          output_formats: 'json,sarif'
          platform_type: 'dockerfile,kubernetes,terraform'
          exclude_paths: 'node_modules'
          # removed fail_on so it never blocks pipeline

      - name: Upload SARIF to Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()   # ✅ always runs even if KICS errors
        with:
          sarif_file: results-dir/results.sarif

      - name: Upload All Results as Artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: kics-results
          path: results-dir/